FROM python:3.10-slim

WORKDIR /app

# Обновляем pip
RUN pip install --upgrade pip

# Копируем requirements
COPY requirements.txt .

# Устанавливаем зависимости с выводом ошибок
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код
COPY src/ ./src/

EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

