cluster.name: sre-diploma-cluster
node.name: os-node-1

network.host: 0.0.0.0
http.port: 9200

bootstrap.memory_lock: false

path.data: /usr/share/opensearch/data
path.logs: /usr/share/opensearch/logs

http.cors.enabled: true
http.cors.allow-origin: "*"
