# infra/opensearch/opensearch.yml
cluster.name: sre-diploma-cluster
node.name: os-node-1

# Network
network.host: 0.0.0.0
http.port: 9200

# Memory
bootstrap.memory_lock: false
cluster.initial_master_nodes: ["os-node-1"]
discovery.seed_hosts: ["127.0.0.1"]

# Security - отключено для dev
plugins.security.disabled: true

# Path (опционально)
path.data: /usr/share/opensearch/data
path.logs: /usr/share/opensearch/logs


